version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    container_name: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
  nestjs:
    build:
      context: ./project
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./project:/app
    depends_on:
      - postgres
    container_name: nestjs

  reacr-admin:
    build:
      context: ./react-admin
      dockerfile: dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./react-admin:/app
    depends_on:
      - nestjs
    command: npm start
    restart:
      always
    container_name: react-admin
    environment:
      - WDS_SOCKET_PORT=0

volumes:
  postgres:

